/* eslint-disable */
/**
 * STUB — Generated by `npx convex dev`.
 * Run `npx convex dev` to replace with real generated types.
 * This stub exists so the Next.js build passes without a Convex deployment.
 */

import type { FunctionReference } from "convex/server";

type AnyFn = FunctionReference<any, any, any, any>;

export const api = {
  weatherScheduling: {
    getJobsForDate: {} as AnyFn,
    getJobsForDateRange: {} as AnyFn,
    getWeatherStatusForJobs: {} as AnyFn,
    getTradePreset: {} as AnyFn,
    getWeatherWindows: {} as AnyFn,
    getWeatherActions: {} as AnyFn,
    getDashboardStats: {} as AnyFn,
    getNotificationLog: {} as AnyFn,
    getAllTradePresets: {} as AnyFn,
    getActiveBusinesses: {} as AnyFn,
    updateJobWeatherStatus: {} as AnyFn,
    rescheduleJob: {} as AnyFn,
    logWeatherAction: {} as AnyFn,
    logWeatherCheck: {} as AnyFn,
    logNotification: {} as AnyFn,
    upsertWeatherRules: {} as AnyFn,
    overrideJobStatus: {} as AnyFn,
    cacheWeatherWindows: {} as AnyFn,
  },
  seedData: {
    seedDefaultPresets: {} as AnyFn,
  },
  actions: {
    runWeatherCheck: {
      runWeatherCheck: {} as AnyFn,
    },
    batchWeatherCheck: {
      batchWeatherCheck: {} as AnyFn,
    },
    sendSms: {
      sendSms: {} as AnyFn,
    },
    sendEmail: {
      sendEmail: {} as AnyFn,
    },
    sendNotifications: {
      sendRescheduleNotifications: {} as AnyFn,
    },
  },
};

export const internal = {};
