/* eslint-disable */
/**
 * STUB — Generated by `npx convex dev`.
 * Run `npx convex dev` to replace with real generated types.
 */
export {
  queryGeneric as query,
  mutationGeneric as mutation,
  actionGeneric as action,
  internalQueryGeneric as internalQuery,
  internalMutationGeneric as internalMutation,
  internalActionGeneric as internalAction,
  httpActionGeneric as httpAction,
} from "convex/server";
